/**
 * 🔴 ROW 5 — THE GUARDS AROUND THE CLUSTERER. GUARD, NOT EVIDENCE.
 *
 * Rewritten 22 September 2026 under the RETIRED_CONTAMINATED rulings (_handoffs a5452ee, clarified by f4367b1). The Row 5
 * held-out population and the reference that scored it are retired. This file no longer names a real query or a real
 * expected label.
 *
 * TWO KINDS OF TEST, NEVER MIXED:
 *   REAL — the production path over the real store. Counts, outcome categories and reconciliation only.
 *   SYNTHETIC — NOT REAL EVIDENCE. Generated by test/support/synthetic-queries.mjs (its RULE) plus the declared
 *          scenario rule below. A synthetic test proves that a MECHANISM fires; it never proves real-world
 *          effectiveness. SEEDS: 7201 (split causes), 7301 (empty population), 7401 (three-world controls),
 *          7501 (reference-leak census).
 */
import test from "node:test";
import { declaredWorld } from "./helpers/declared-world.mjs";
/* F02: every entry point decides its tenant first — the runs below go through a DECLARED FIXTURE WORLD (never the real population). */
const WORLD = declaredWorld();
process.on("exit", () => WORLD.cleanup());
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { spawnSync } from "node:child_process";

import { classify } from "../src/checklist/classification.mjs";
import { createJsonlStore } from "../src/evidence/store.mjs";
import { row5, QUERY_OBSERVATION } from "../src/discovery/row5.mjs";
import { clusterIntents, clusteringErrors, heldOutCheck, buildRecord, splitCauses, place, idfOf, normalise, isHeldOut, sha, SPLIT_CAUSES } from "../src/discovery/intent-clusters.mjs";
import { LEXICON } from "../subjects/almiworld-estate/config/intent-lexicon.mjs";
import { INTENT_REFERENCE, AMBIGUOUS, REFERENCE_STATUS } from "../config/discovery/intent-reference.mjs";
import { syntheticCorpus, mulberry32, EVIDENCE_CLASS, RULE } from "./support/synthetic-queries.mjs";

const REPO = new URL("../", import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1");
const RECORDS = createJsonlStore(join(REPO, "runs", "evidence", "evidence.jsonl")).readAll();
const run5 = (records = RECORDS) => row5({ records, lexicon: LEXICON, reference: INTENT_REFERENCE, ambiguous: AMBIGUOUS, referenceStatus: REFERENCE_STATUS });
const R = run5();
const HUMAN = R.population.human;
const limbs = (errs) => [...new Set(errs.map((e) => e.limb))];
const withRows = (rows) => RECORDS.map((r) => (r.record_type === "observation" && r.observation_id === QUERY_OBSERVATION ? { ...r, value: { ...r.value, rows } } : r));
const OBS_ROWS = RECORDS.find((r) => r.record_type === "observation" && r.observation_id === QUERY_OBSERVATION).value.rows;

/**
 * THE SPLIT SCENARIO RULE (declared, deterministic). From syntheticCorpus({ seed, intents: 6, queriesPerIntent: 6 }):
 *   (1) take intent 01's first in-sample query's content key and append TWO fresh 4-syllable words (never in the corpus,
 *       never declared); keep the first such candidate the hold-out rule holds out, and add it to intent 01;
 *   (2) make a new intent from two fresh words a, b: candidates "a b <fresh>" / "b a <fresh>" alternate, and the first
 *       two the hold-out rule holds out become its only members.
 * The fresh words come from mulberry32(seed + 1) over the same syllable alphabet as the corpus.
 */
function splitScenario(seed) {
  const S = syntheticCorpus({ seed, intents: 6, queriesPerIntent: 6 });
  const rnd = mulberry32(seed + 1);
  const C = "bdfgklmnprstvz", V = "aeiou", pick = (s) => s[Math.floor(rnd() * s.length)];
  const fresh = () => `q${pick(C)}${pick(V)}${pick(C)}${pick(V)}${pick(C)}${pick(V)}${pick(C)}${pick(V)}`;
  const rows = [...S.rows];
  const reference = JSON.parse(JSON.stringify(S.reference));
  const [id1] = Object.keys(reference);
  const base = normalise(reference[id1].members.filter((q) => !isHeldOut(q))[0], S.lexicon).key.filter((t) => !t.startsWith("<"));
  let unknownQ;
  for (let i = 0; i < 200 && !unknownQ; i += 1) { const q = `${base.join(" ")} ${fresh()} ${fresh()}`; if (isHeldOut(q)) unknownQ = q; }
  rows.push({ query: unknownQ, impressions: 1, clicks: 0 });
  reference[id1].members.push(unknownQ);
  const a = fresh(), b = fresh(), orphans = [];
  for (let i = 0; i < 400 && orphans.length < 2; i += 1) { const q = i % 2 ? `${a} ${b} ${fresh()}` : `${b} ${a} ${fresh()}`; if (isHeldOut(q)) orphans.push(q); }
  for (const q of orphans) rows.push({ query: q, impressions: 1, clicks: 0 });
  reference["synthetic-intent-orphan"] = { members: orphans };
  return { rows, reference, lexicon: S.lexicon, unknownQ, orphans, id1 };
}

/* ═════════ THE SPLIT CAUSES ═════════ */

test("SYNTHETIC · seed 7201 — every split carries a named reason code; an unknown word is listed, never labelled", () => {
  const { rows, reference, lexicon, unknownQ, orphans, id1 } = splitScenario(7201);
  assert.ok(unknownQ && orphans.length === 2, "the scenario rule must produce its three held-out additions");
  const h = heldOutCheck(rows, lexicon, reference, {});
  const record = buildRecord(rows, h, lexicon);
  const causes = splitCauses({ humanRows: rows, record, heldOut: h, reference, ambiguous: {}, lexicon });
  assert.deepEqual(causes.map((c) => [c.intent, c.codes]), [[id1, ["SPLIT_UNKNOWN_TOKEN"]], ["synthetic-intent-orphan", ["SPLIT_NO_IN_SAMPLE_MEMBER", "SPLIT_UNKNOWN_TOKEN"]]]);
  const apart = causes[0].apart;
  assert.deepEqual(apart.map((x) => x.original), [unknownQ]);
  assert.equal(apart[0].unknownTokens.length, 2, "both fresh words are listed as UNKNOWN");
  for (const c of causes) for (const x of c.apart) for (const code of x.codes) assert.ok(Object.hasOwn(SPLIT_CAUSES, code), code);
  // the causes cover exactly the splits acceptance reports
  const errs = clusteringErrors({ humanRows: rows, record, heldOut: h, reference, ambiguous: {}, lexicon });
  assert.deepEqual(causes.map((c) => c.intent), errs.filter((e) => e.limb === "record-split").map((e) => e.why.match(/^intent (\S+)/)[1]).sort());
});

test("REAL — no lawful reference: the split causes are UNAVAILABLE (null), never an empty list that reads as no splits", () => {
  assert.equal(R.splitCauses, null);
  assert.equal(R.scoring.state, "REFUSED");
  assert.equal(R.scoring.code, "HELD_OUT_REFERENCE_RETIRED");
});

test("REAL — the runner says the causes are unavailable, from the production path", () => {
  const out = spawnSync(process.execPath, WORLD.argv([join(REPO, "bin", "intent-clusters.mjs"), "--check", "--subject=almiworld-estate"]), { encoding: "utf8", env: WORLD.envWith() });
  assert.equal(out.status, 1);
  assert.match(out.stdout, /SPLIT CAUSES — 🔴 UNAVAILABLE \(HELD_OUT_REFERENCE_RETIRED\)/);
});

/* ═════════ AN EMPTY POPULATION IS NOT A PASS ═════════ */

test("🔴 an empty human population is refused by its own branch", () => {
  const S = syntheticCorpus({ seed: 7301 });
  const h = heldOutCheck([], S.lexicon, S.reference, {});
  const errs = clusteringErrors({ humanRows: [], record: buildRecord([], h, S.lexicon), heldOut: h, reference: S.reference, ambiguous: {} });
  assert.deepEqual(limbs(errs), ["empty-population"]);
  assert.match(errs[0].why, /^no human query row was given/);
});

test("SYNTHETIC · seed 7301 — a scored population of 0 under a LAWFUL reference (every row ambiguous) is refused", () => {
  const S = syntheticCorpus({ seed: 7301 });
  const allAmb = Object.fromEntries(S.rows.map((r) => [r.query, "control: all ambiguous"]));
  const h = heldOutCheck(S.rows, S.lexicon, S.reference, allAmb);
  const errs = clusteringErrors({ humanRows: S.rows, record: buildRecord(S.rows, h, S.lexicon), heldOut: h, reference: S.reference, ambiguous: allAmb, lexicon: S.lexicon });
  assert.deepEqual(limbs(errs), ["empty-population"]);
});

test("🟢 REAL — the real population is not empty: 329 human rows, and the empty-population limb stays silent on it", () => {
  assert.equal(HUMAN.length, 329);
  assert.equal(limbs(R.errors).includes("empty-population"), false);
});

/* ═════════ DETERMINISM, MEASURED ═════════ */

test("🔴 REAL — the production path over the store's order and two reorderings is BYTE-IDENTICAL", () => {
  const body = (r) => JSON.stringify({ record: r.record, errors: r.errors, heldOut: r.heldOut, splitCauses: r.splitCauses, ruleExcluded: r.ruleExcluded, scoring: r.scoring });
  const a = body(R);
  assert.equal(body(run5(withRows([...OBS_ROWS].reverse()))), a, "reversed input changed the output");
  assert.equal(body(run5(withRows([...OBS_ROWS.slice(100), ...OBS_ROWS.slice(0, 100)]))), a, "rotated input changed the output");
});

/* ═════════ FITTING READS NEITHER THE REFERENCE NOR THE HELD-OUT ROWS ═════════ */

test("🔴 REFERENCE-LEAK CENSUS — the clusterer imports no reference, and real fitting is identical under every reference", () => {
  const src = readFileSync(join(REPO, "src", "discovery", "intent-clusters.mjs"), "utf8");
  assert.deepEqual([...src.matchAll(/^import .* from "([^"]+)";$/gm)].map((m) => m[1]), ["node:crypto"]);
  /* The alternates CHANGE THE PARTITION: none at all, an empty one, every IN-SAMPLE row in one intent (built at runtime
   * from in-sample rows only — no retired member), and a synthetic reference (seed 7501) naming none of these rows. */
  const inSample = HUMAN.filter((r) => !isHeldOut(r.query)).map((r) => r.query);
  const fit = (ref) => { const h = heldOutCheck(HUMAN, LEXICON, ref, {}); return JSON.stringify({ c: h.inSampleClusters, p: h.results.map((r) => [r.ref, r.placedIn, r.similarity]) }); };
  const base = fit(null);
  for (const ref of [{}, { all: { members: inSample } }, syntheticCorpus({ seed: 7501 }).reference]) {
    assert.equal(fit(ref), base, "clustering or placement moved with the reference — the reference is read during fitting");
  }
});

test("🔴 REAL — HELD-OUT INTEGRITY: the in-sample clusters are the same with the held-out rows present or removed, and hold none of them", () => {
  const train = HUMAN.filter((r) => !isHeldOut(r.query));
  assert.equal(JSON.stringify(clusterIntents(train, LEXICON)), JSON.stringify(R.heldOut.inSampleClusters));
  assert.equal(R.heldOut.inSampleClusters.some((c) => c.members.some((m) => isHeldOut(m.original))), false);
});

/* ═════════ §6 — THREE WORLDS AND THE CONTROLS · SYNTHETIC, seed 7401 ═════════
 * RULE: words come from syntheticCorpus({ seed: 7401, intents: 8 }) — its intents' content words, taken in order
 * (w[0], w[1], …) — and its generated filler. EDIT-NEAR: a word with its second consonant swapped for the next consonant
 * of the alphabet. VARIANT: a word with 'a' appended (a surface variant with no declared relation). */
const S74 = syntheticCorpus({ seed: 7401, intents: 8 });
const W = Object.values(S74.reference).flatMap((i) => normalise(i.members[0], S74.lexicon).key.filter((t) => /^q/.test(t)));
const w = (i) => W[i];
const FX = { phrases: [], synonyms: {}, filler: S74.lexicon.filler, slotTypes: {}, exclusive: [[w(0), w(1)]] };
const rows = (...qs) => qs.map((query) => ({ query, impressions: 1, clicks: 0 }));
const together = (cs, a, b) => cs.some((c) => c.members.some((m) => m.original === a) && c.members.some((m) => m.original === b));
const nearest = (q, cs) => place(q, cs, FX, idfOf(cs.flatMap((c) => c.members.map((m) => m.key))));
const editNear = (x) => { const cs = "bdfgklmnprstvz"; const i = [...x].findIndex((ch, k) => k > 1 && cs.includes(ch)); return x.slice(0, i) + cs[(cs.indexOf(x[i]) + 1) % cs.length] + x.slice(i + 1); };

test(`SYNTHETIC · ${EVIDENCE_CLASS} — the fixture names its rule and seed`, () => {
  assert.match(RULE, /mulberry32\(seed\)/);
  assert.equal(S74.seed, 7401);
  assert.equal(S74.evidenceClass, EVIDENCE_CLASS);
  assert.ok(W.length >= 16);
});

test("SYNTHETIC · world A — same intent, a structural relation (word order and filler) → JOIN", () => {
  const q1 = `${w(0)} ${w(2)} ${w(3)}`, q2 = `${w(3)} ${S74.lexicon.filler[0]} ${w(2)} ${w(0)}`;
  const cs = clusterIntents(rows(q1, q2, `${w(4)} ${w(5)}`), FX);
  assert.ok(together(cs, q1, q2));
});

test("SYNTHETIC · world B — different intent despite surface likeness (declared exclusive entities) → KEEP SEPARATE", () => {
  const q1 = `${w(0)} ${w(2)} ${w(3)}`, q2 = `${w(1)} ${w(2)} ${w(3)}`;
  assert.equal(together(clusterIntents(rows(q1, q2), FX), q1, q2), false);
});

test("SYNTHETIC · world C — an ambiguous relation (one shared word, below the threshold) → UNKNOWN: NO JOIN", () => {
  const cs = clusterIntents(rows(`${w(0)} ${w(2)} ${w(3)}`, `${w(0)} ${w(2)} ${w(3)}`), FX);
  assert.equal(nearest(`${w(6)} ${w(7)} ${w(8)}`, cs).id, "NEW");
  const p = nearest(`${w(0)} ${w(7)} ${w(8)}`, cs);
  assert.ok(p.avg > 0 && p.avg < 0.5, `the control must be ambiguous, not unrelated: ${p.avg}`);
  assert.equal(p.id, "NEW");
});

test("SYNTHETIC · subset wording, different intent: the shorter key inside the longer does not pull it in", () => {
  const cs = clusterIntents(rows(`${w(2)} ${w(3)}`, `${w(2)} ${w(3)}`), FX);
  assert.equal(nearest(`${w(2)} ${w(3)} ${w(9)} ${w(10)}`, cs).id, "NEW");
});

test("SYNTHETIC · the same rare anchor, different intents, stay apart", () => {
  const q1 = `${w(4)} ${w(5)} ${w(11)}`, q2 = `${w(6)} ${w(7)} ${w(11)}`;
  assert.equal(together(clusterIntents(rows(q1, q2), FX), q1, q2), false);
});

test("SYNTHETIC · edit-near words stay apart — no fuzzy matching joins them", () => {
  const q1 = `${w(12)} ${w(13)}`, q2 = `${editNear(w(12))} ${w(13)}`;
  assert.notEqual(w(12), editNear(w(12)));
  assert.equal(together(clusterIntents(rows(q1, q2), FX), q1, q2), false);
});

test("SYNTHETIC · surface variants with no declared relation stay apart", () => {
  const q1 = `${w(14)} ${w(15)}`, q2 = `${w(14)}a ${w(15)}`;
  assert.equal(together(clusterIntents(rows(q1, q2), FX), q1, q2), false);
});

test("SYNTHETIC · a nearest neighbour broken by a better competing family: the query goes to the better one", () => {
  const two = `${w(2)} ${w(3)}`, three = `${w(2)} ${w(3)} ${w(4)}`;
  const cs = clusterIntents(rows(two, two, three, three), FX);
  const better = cs.find((c) => c.members.some((m) => m.original === three));
  assert.equal(nearest(three, cs).id, better.id);
});

test("SYNTHETIC · a transitive chain whose endpoints differ does not close into one cluster", () => {
  const a = `${w(2)} ${w(3)} ${w(4)}`, b = `${w(3)} ${w(4)} ${w(5)}`, c = `${w(4)} ${w(5)} ${w(6)}`;
  assert.equal(together(clusterIntents(rows(a, b, c), FX), a, c), false);
});

test("🟢 REAL — operator rows are unchanged: the 8 store operator strings are kept verbatim and none enters the record", () => {
  assert.equal(R.population.operators.length, 8);
  for (const o of R.population.operators) assert.ok(OBS_ROWS.some((r) => r.query === o.query));
  const inRecord = new Set(R.record.flatMap((c) => c.members.map((m) => m.ref)));
  for (const o of R.population.operators) assert.equal(inRecord.has(sha(o.query)), false);
});

/* ═════════ RUNTIME, AND THE LEDGER ═════════ */

test("🟢 REAL — RUNTIME: the production path over the measured population (329 human rows) completes within 10 s", () => {
  const t0 = process.hrtime.bigint();
  run5();
  assert.ok(Number(process.hrtime.bigint() - t0) / 1e9 < 10);
});

test("🔴 row 5 stays FAILED, its blocker named by class and count, its unlock checkable by one command", () => {
  const row = classify()[5];
  assert.equal(row.state, "FAILED");
  assert.match(row.blocker, /^ENGINE_CAPABILITY_GAP \+ SUBJECT_VOCABULARY_DEFERRED_TO_SUBJECT_PHASE — /);
  assert.match(row.blocker, /ENGINE_CAPABILITY_GAP, 3 families/);
  assert.match(row.blocker, /SUBJECT_VOCABULARY_DEFERRED_TO_SUBJECT_PHASE, 5 families/);
  assert.match(row.unlockCondition, /node bin\/intent-clusters\.mjs --check/);
  assert.equal(row.ruling, "_handoffs/AlmiVisibility_CC_COMMAND_2026-09-22_ROW5_COMPLETE.md");
});
