/**
 * 🔴 F07 §5.6 · THE MANDATORY-READING MANIFEST — DECLARED (23 September 2026).
 *
 * The files a builder or a command must read: every CURRENT authority record the F05 register resolves, every
 * acceptance source the F-board pins, and the configuration the board and the authority loaders read. Checked by
 * src/governance/mandatory-reading.mjs against the loaders in BOTH directions — a missing required source and a
 * sealed or protected entry each turn the check RED. Generated from the loaders at corpus governance commit
 * 1429928b4813 (now 2026-09-24); regenerate after every corpus migration — the
 * check fails loudly until you do, which is the point.
 *
 * Paths only. No content of any listed file is copied here.
 */
export const BOARD_AND_AUTHORITY_CONFIG = Object.freeze(["config/fboard/acceptances.mjs","config/fboard/capabilities.mjs","config/fboard/crosswalk.mjs","config/fboard/f-board.mjs","config/authority/corpus.mjs","config/authority/inclusion.mjs","config/evidence-roles.mjs"]);
export const MANDATORY_READING = Object.freeze([
  Object.freeze({ repo: "engine", path: "config/authority/corpus.mjs", loader: "F-board configuration" }),
  Object.freeze({ repo: "engine", path: "config/authority/inclusion.mjs", loader: "F-board configuration" }),
  Object.freeze({ repo: "engine", path: "config/evidence-roles.mjs", loader: "F-board configuration" }),
  Object.freeze({ repo: "engine", path: "config/fboard/acceptances.mjs", loader: "F-board configuration" }),
  Object.freeze({ repo: "engine", path: "config/fboard/capabilities.mjs", loader: "F-board configuration" }),
  Object.freeze({ repo: "engine", path: "config/fboard/crosswalk.mjs", loader: "F-board configuration" }),
  Object.freeze({ repo: "engine", path: "config/fboard/f-board.mjs", loader: "F-board configuration" }),
  Object.freeze({ repo: "engine", path: "PASS_BOUNDARIES_AMENDMENT_1.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "engine", path: "PASS_BOUNDARIES_AMENDMENT_2.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "engine", path: "PASS_BOUNDARIES_AMENDMENT_3.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "engine", path: "PASS_BOUNDARIES_AMENDMENT_4.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "engine", path: "PASS_BOUNDARIES_AMENDMENT_5.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "engine", path: "PASS_BOUNDARIES_AMENDMENT_6.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "engine", path: "PASS_BOUNDARIES_AMENDMENT_7.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "engine", path: "PASS_BOUNDARIES_SOURCE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_BETA_G_RULING_9_AMBIGUOUS_2026-09-13_NIGHT.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-19_ERROR_REGISTER_AND_PERSISTENCE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-19_ROW17_CLOSE_OR_HALT.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-19_ROW9_CLOSE_OR_HALT.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-19_SELECT_AND_CLOSE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-20_ROW6_CLOSE_OR_HALT.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-20_ROW6_OWNER_INPUT_AND_CLOSE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-21_AMEND_ROW61_AND_RESUME_ROW6.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-21_ROW25_COMPLETE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-21_ROW4_COMPLETE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-21_ROW50_COMPLETE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-21_ROW50_OWNER_REOPEN_APPLIED.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-21_ROW6_DEMAND_RESEARCH_AND_CLOSE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-22_F05_CHAIN_PART3_REMEDIATION.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-22_F05_CHAIN_PART4_OWNER_ANSWERS.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-22_F05_CURRENT_AUTHORITY_REGISTER_CHAIN.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-22_F08_CONTRADICTORY_EVIDENCE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-22_ROW5_COMPLETE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-23_F07_COMPLETE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-23_F07_SINK_REPAIR.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-23_F08_COMPLETE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-24_BRANCH_DISPOSITION.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-24_AUDIT_STORE_PRIMITIVES.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-24_F01_COMPLETE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-24_F02_POST_MERGE_PREREQUISITES.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-24_F02_TENANT_ISOLATION.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-24_F06_COMPLETE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-24_F06_CORRECTION.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-24_PRIMITIVES_AND_SESSION_SAVE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-25_F02_DISPOSITION.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-25_F03_SUBJECT_ROOT_AND_CONNECTOR_REGISTRY.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-25_F03_CLOSE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-25_F04_ROLES_PERMISSIONS_APPROVALS.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-25_F04_POST_MERGE_CLOSE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-25_F09_CROSS_CLIENT_PORTABILITY.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-25_F09_OPTION_A_EXTERNAL_SUBJECT.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-25_F09_CLOSE_OUT.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-25_F10_COMPLETE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-25_F10_DEPENDENCY_PREPARATION.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-25_F10_PREP_ROUND2.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-25_F10_PREP_ROUND3.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-25_F07_NARROW_AMENDMENT_REISSUE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-26_F07_AMENDMENT_1_POST_MERGE_CLOSE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-26_SHEET_SAFE_LABELS.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-26_F10_OWNER_SHEET.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-26_RA4_SAFE_LABELS_RULING.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-26_F10_OWNER_INPUT_HOLD.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-26_F10_OWNER_DECISION_GATE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-26_F10_RESOLVE_GATE_AND_ADVANCE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-26_F10_OWNER_DIRECTION_OF1_OF4.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-26_F10_FREEZE_BUILD_SELECT.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-26_F07_AMENDMENT_2_MARKING_KEY_EVALUATOR.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F10_OWNER_DECISION_GATE_2026-09-26.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F10_OWNER_DECISIONS_STATUS_2026-09-26.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-26_RA4_SAFE_DISPLAY_LABELS.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-26_F10_RESUME_EXTERNAL_SEALED_KEY.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-26_F10_STORAGE_S.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-26_F10_SCORER_ROUTE_AND_MISSING_OUTPUT.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-26_F10_ALLOCATION_ADOPTED.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-26_F10_OF4_AMENDMENT_1_DECIDED.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-26_F10_PR165_CLOSE_AND_C7_AMENDMENT.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-26_F10_C7_SCOPE_DECISION.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-26_F10_C7_BAR_APPROVAL_FREEZE_AND_IMPLEMENT.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-26_F10_C7_COMPLETION_PATH.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-26_REPAIR_D_RECORDER_1_THEN_RESUME.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-26_168_MERGED_CONTINUE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-27_CONTINUE_F10_AFTER_169.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-27_POST_MERGE_170_STORAGE_S_BOUNDARY_THEN_SELECTION.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-27_WITHDRAW_CI_SCOPE_PROCEED_UNDER_STORAGE_S.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-27_REPAIR_171_BEFORE_MERGE_PRESERVE_SEAL.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F01_FROZEN_ACCEPTANCE_2026-09-24.md", loader: "F-board acceptance F01" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F02_ACCEPTANCE_2026-09-24.md", loader: "authority register (CURRENT record) — the original F02 acceptance, amended by Amendment 1" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F02_ACCEPTANCE_AMENDMENT_1_2026-09-25.md", loader: "F-board acceptance F02" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F03_FROZEN_ACCEPTANCE_2026-09-25.md", loader: "F-board acceptance F03" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F04_ACCEPTANCE_2026-09-25.md", loader: "authority register (CURRENT record) — the original F04 acceptance, amended by Amendment 1" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F04_ACCEPTANCE_AMENDMENT_1_2026-09-25.md", loader: "F-board acceptance F04" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F09_ACCEPTANCE_2026-09-25.md", loader: "F-board acceptance F09" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F10_ACCEPTANCE_2026-09-26.md", loader: "authority register (CURRENT record) — the original F10 acceptance, amended by Amendment 1" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F10_ACCEPTANCE_AMENDMENT_1_2026-09-26.md", loader: "authority register (CURRENT record) — Amendment 1, amended by Amendment 2" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F10_ACCEPTANCE_AMENDMENT_2_2026-09-27.md", loader: "authority register (CURRENT record) — Amendment 2, amended by Amendment 3" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F10_ACCEPTANCE_AMENDMENT_3_2026-09-28.md", loader: "F-board acceptance F10" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-27_PR171_AUDIT_INCIDENT_RECONCILE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-27_FINISH_F10_ON_FROZEN_CONTRACT.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-27_FINISH_F10_CONTINUE_AFTER_171_MERGE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-27_F10_REAL_HELDOUT_EVALUATION.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-28_PRODUCT_DIRECTION_AND_REUSE_MEASUREMENT.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-28_APPLY_BEST_PAGE_RECIPE_V3_TO_REUSE_CENSUS.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-27_CORRECT_V3_ADOPTION_AND_RECOVER_F10.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-28_V3_ADOPTION.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-28_STOP_F10_A3_PATH_RECONCILE_TWO_BOARDS.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-28_61_89_ARTIFACT_TRANSFER_FEATURE_LISTS_NEXT_FEATURE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-28_COMPLETE_ROWS_WITH_WORK_ONE_BY_ONE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-28_SPECIFICATION_AMENDMENT_1_F90.md", loader: "authority register (CURRENT record) — Specification Amendment 1: F90, denominator 90" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F14_ACCEPTANCE_2026-09-28.md", loader: "authority register (CURRENT record) — F14 acceptance, frozen; F14 PAUSED by owner decision 2" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F19_ACCEPTANCE_2026-09-28.md", loader: "authority register (CURRENT record) — F19 acceptance, frozen; F19 PARKED pending the owner's GREEN for a live crawl" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F06_FROZEN_ACCEPTANCE_2026-09-24.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F07_FROZEN_ACCEPTANCE_2026-09-23.md", loader: "F-board acceptance F07" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F07_ACCEPTANCE_AMENDMENT_1_2026-09-25.md", loader: "authority register (CURRENT record) — Amendment 1, amended by Amendment 2" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F07_ACCEPTANCE_AMENDMENT_2_2026-09-26.md", loader: "authority register (CURRENT record) — Amendment 2, amended by Amendment 3" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F07_ACCEPTANCE_AMENDMENT_3_2026-09-26.md", loader: "F-board acceptance F07" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_FEATURE_MASTER_COMMAND_ROW1_2026-09-18.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_FEATURE_MASTER_COMMAND_ROW5_2026-09-18.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_FEATURE_MASTER_COMMAND_ROW9_2026-09-18.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_CLARIFICATION_2026-09-19_PRODUCT_PRIORITY_AND_ISOLATION_BOUNDARY.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_DECISION_2026-09-19_ROW1_CLOSED_BLOCKED_PROVED.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_DECISION_2026-09-22_ROW50_PRODUCT_BOUNDARY.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_DECISION_2026-09-24_F02_RELOCATE_SINGLE_CLIENT_TOOLS.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-13_AMENDMENT_4_SCOPE_OPENS.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-13_AMENDMENT_5_PORTABLE_PAGE_CONSTRUCTION.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-19_ARTEFACT_PERSISTENCE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-19_COMMIT_MECHANISM_SCOPE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-19_D2_MIXED_LIMB_SPLIT.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-19_U1_ROW1_COST_ISOLATION_SEMANTICS.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-21_ROW4_CONJUNCTION_AND_REASONING.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-21_ROW50_LABEL_ON_FACE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-21_TENANT_RESOURCE_ATTACHMENTS.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-22_BOARD_AUTHORITY.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-22_F05_ACCEPTANCE.md", loader: "F-board acceptance F05" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-22_F08_ACCEPTANCE.md", loader: "F-board acceptance F08" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-22_F08_GOVERNED_WRITE_BOUNDARY.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-22_HELDOUT_ROLE_SCOPE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-22_RETIRED_CONTAMINATED_HELDOUT.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-23_F08_TARGET_AWARE_DURABILITY.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-24_AUDIT_STORE_ONLY_PRIMITIVES.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-24_F02_RESOURCE_ATTACHMENTS.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_A_2026-09-15_READ_ONLY_DEPLOY_KEY.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULINGS_2026-09-14_ROWS_5_6_STATES.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-25_F04_ZERO_APPROVED_ACTION_POPULATION.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-25_F02_DISPOSITION.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_STATUS_SEMANTICS_RULING_RECORD_2026-09-18.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_ROW61_OWNER_DECISION_2026-09-15.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "CC_COMMAND_2026-09-13_SESSION_SAVE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "CC_COMMAND_2026-09-14_OPTION_A_SUBJECT_REGISTRY_LEAVES_THE_REPO.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "CC_COMMAND_2026-09-14_ROWS_5_6_INTENT_CLUSTERING_AXIS_DISCOVERY.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "CC_COMMAND_2026-09-15_GAP1_UNGATED_WRITERS.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "CC_COMMAND_2026-09-15_GAP3_ARCHIVE_CORPUS_OUT_ROW36.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "CC_COMMAND_2026-09-15_RENDERER_LIVE_ONCE_ON_MAIN.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "CC_COMMAND_2026-09-15_ROW25_PAGE_QUALITY_GATE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "CC_COMMAND_2026-09-15_ROW3_SEARCH_LANGUAGE_OWNED_HALF.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "CC_COMMAND_2026-09-15_ROW36_DCRW4_GUARD.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "CC_COMMAND_2026-09-15_ROW36_DESTRUCTIVE_GUARDS.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "CC_COMMAND_2026-09-15_ROW4_LOCALIZED_THINKING.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "CC_COMMAND_2026-09-15_ROW7_MARKET_MEASUREMENT_OWNED_HALF.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "CC_COMMAND_AMENDMENT_3_ROWS_59_60.md", loader: "authority register (CURRENT record)" }),
  /* RR-82 (28 Sep 2026): the corpus re-migrated at _handoffs b443e5e — the 17 sources the loaders now read and this manifest lacked, computed by manifestErrors (never typed from memory). */
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-28_RR-76_PREBUILD_REVIEW_OWNER_ADDITION_GAP_G.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-28_RR-76_PREBUILD_REVIEW_OWNER_ADDITION_GAP_H.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-28_RR-76_PREBUILD_REVIEW_OWNER_CORRECTION_GAP_H_THREE_STATES.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-28_RR-76_PREBUILD_REVIEW_THEN_COMPLETE_ROWS.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-28_RR-76_SAVE_AND_PAUSE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-28_RR-78_RESOLVE_THE_PREBUILD_REVIEW_BEFORE_F77.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-28_RR-79_ADDITION_5_THE_MISSING_DOCUMENT_NOW_AVAILABLE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-28_RR-79_APPLY_THE_OWNERS_NEW_DIRECTION_ON_TOP_OF_RR-78.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-28_RR-80_RESOLVE_AUTHORITY_AND_FINISH_THE_PREBUILD_SPECIFICATION.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-28_RR-81_CLOSE_THE_LIST_REVIEW_COMPLETE_F77_NEXT.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-28_RR-82_F77_POST_MERGE_CLOSEOUT.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F07_ACCEPTANCE_AMENDMENT_4_2026-09-28.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F14_ACCEPTANCE_AMENDMENT_1_2026-09-28.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F77_ACCEPTANCE_2026-09-28.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F77_ACCEPTANCE_AMENDMENT_1_2026-09-28.md", loader: "F-board acceptance F77" }),
  /* RR-83 (28 Sep 2026): the F34 command, a CURRENT record after the corpus re-migration at _handoffs 53f74b4, and F34's frozen acceptance. */
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-28_RR-83_F34_REUSE_AND_COMPLETE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F34_ACCEPTANCE_2026-09-28.md", loader: "F-board acceptance F34" }),
  /* RR-84 (29 Sep 2026): the F33 command, a CURRENT record after the corpus re-migration at _handoffs 9dc9bc2, and F33's frozen acceptance. */
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-29_RR-84_CLOSE_180_THEN_F33.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F33_ACCEPTANCE_2026-09-29.md", loader: "F-board acceptance F33" }),
  /* RR-85 (29 Sep 2026): the F31 command, a CURRENT record after the corpus re-migration at _handoffs 3a8f7ba, and F31's frozen acceptance. */
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-29_RR-85_F31_VERIFY_THE_EXISTING_PAGE_INVENTORY.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F31_ACCEPTANCE_2026-09-29.md", loader: "F-board acceptance F31" }),
  /* RR-86 (29 Sep 2026): the next-feature command, a CURRENT record after the corpus re-migration at _handoffs 804ebd1, and F21's frozen acceptance. */
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-29_RR-86_NEXT_ALMIVISIBILITY_FEATURE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F21_ACCEPTANCE_2026-09-29.md", loader: "F-board acceptance F21" }),
  /* RR-87 (29 Sep 2026): the standing continuous-build command, a CURRENT record after the corpus re-migration at _handoffs 2635153, and F36's frozen acceptance. */
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-29_RR-87_CONTINUOUS_BUILD.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F36_ACCEPTANCE_2026-09-29.md", loader: "F-board acceptance F36" }),
  /* RR-88 (29 Sep 2026): close #184, then F35 — a CURRENT record after the corpus re-migration at _handoffs da659bd, and F35's frozen acceptance. */
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-29_RR-88_CLOSE_184_THEN_F35.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F35_ACCEPTANCE_2026-09-29.md", loader: "F-board acceptance F35" }),
  /* RR-87 row 3 (29 Sep 2026): F32's frozen acceptance, a CURRENT record after the corpus re-migration at _handoffs 0d0f354. */
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F32_ACCEPTANCE_2026-09-29.md", loader: "F-board acceptance F32" }),
  /* RR-89 (29 Sep 2026): owner direction, then the F35 MERGE repair — a CURRENT record after the corpus re-migration at _handoffs 2f010f3. */
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-29_RR-89_OWNER_DIRECTION_THEN_REPAIR_F35_MERGE.md", loader: "authority register (CURRENT record)" }),
  /* RR-90 (29 Sep 2026): F39 — a CURRENT record after the corpus re-migration at _handoffs 90e798d, and F39's frozen acceptance. */
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-29_RR-90_F39_NEXT_STANDALONE_FEATURE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F39_ACCEPTANCE_2026-09-29.md", loader: "F-board acceptance F39" }),
  /* RR-87 continuous build (per RR-90's override), 29 Sep 2026: F41's frozen acceptance, a CURRENT record after the re-migration at _handoffs 454396e. */
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F41_ACCEPTANCE_2026-09-29.md", loader: "F-board acceptance F41" }),
  /* RR-91 (29 Sep 2026, with its resumption): a CURRENT record after the re-migration at _handoffs 6c7627a, and F43's frozen acceptance. */
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-29_RR-91_CLOSE_188_189_THEN_F43.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F43_ACCEPTANCE_2026-09-29.md", loader: "F-board acceptance F43" }),
  /* RR-92 (29 Sep 2026): a CURRENT record after the re-migration at _handoffs 25c7f49, and F82's frozen acceptance. */
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-29_RR-92_CONTINUE_THE_STANDALONE_PRODUCT.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F82_ACCEPTANCE_2026-09-29.md", loader: "F-board acceptance F82" }),
  /* RR-92, F48 (29 Sep 2026): its original acceptance (a CURRENT record) and Amendment 1 (the board's acceptance), after the re-migration at _handoffs 7f212cd. */
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F48_ACCEPTANCE_2026-09-29.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F48_ACCEPTANCE_AMENDMENT_1_2026-09-29.md", loader: "F-board acceptance F48" }),
  /* RR-93, F78 (29 Sep 2026): the command (a CURRENT record) and F78's acceptance, after the migration at _handoffs a1885de. */
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-29_RR-93_CONTINUE_AFTER_21_90.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F78_ACCEPTANCE_2026-09-29.md", loader: "F-board acceptance F78" }),
  /* RR-93, F79 (29 Sep 2026): its original acceptance (a CURRENT record) and Amendment 1 (the board's acceptance), after the migration at _handoffs 60dee9b. */
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F79_ACCEPTANCE_2026-09-29.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F79_ACCEPTANCE_AMENDMENT_1_2026-09-29.md", loader: "F-board acceptance F79" }),
  /* RR-93, F55 (29 Sep 2026): its acceptance, after the migration at _handoffs 7323446. */
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F55_ACCEPTANCE_2026-09-29.md", loader: "F-board acceptance F55" }),
  /* RR-94, F45 (30 Sep 2026): the command (a CURRENT record) and F45's acceptance, after the migration at _handoffs dcb9fbb. */
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-29_RR-94_CONTINUE_FROM_23_90.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F45_ACCEPTANCE_2026-09-30.md", loader: "F-board acceptance F45" }),
  /* RR-95, F26 (30 Sep 2026): the command (a CURRENT record) and F26's acceptance, after the migration at _handoffs b1a94e7. */
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-30_RR-95_CLOSE_F45_CONTINUE_F26.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F26_ACCEPTANCE_2026-09-30.md", loader: "F-board acceptance F26" }),
  /* RR-96, F46 (30 Sep 2026): the command (a CURRENT record) and F46's acceptance, after the migration at _handoffs 2e76216. */
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-30_RR-96_CLOSE_197_CONTINUE_F46.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F46_ACCEPTANCE_2026-09-30.md", loader: "F-board acceptance F46" }),
  /* RR-96 continuous build, F47 (30 Sep 2026): its acceptance, after the migration at _handoffs ccd4c1e. */
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F47_ACCEPTANCE_2026-09-30.md", loader: "F-board acceptance F47" }),
  /* RR-96 continuous build, F20 (30 Sep 2026): its acceptance, after the migration at _handoffs f566059. */
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F20_ACCEPTANCE_2026-09-30.md", loader: "F-board acceptance F20" }),
  /* RR-96 continuous build, F29 (30 Sep 2026): its acceptance, after the migration at _handoffs c8eee0c. */
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F29_ACCEPTANCE_2026-09-30.md", loader: "F-board acceptance F29" }),
  /* RR-97, F73 (30 Sep 2026): the command (a CURRENT record) and F73's acceptance, after the migration at _handoffs 366476c. */
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-30_RR-97_CONTINUE_FROM_29_90_ASSESS_F73.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F73_ACCEPTANCE_2026-09-30.md", loader: "F-board acceptance F73" }),
  /* RR-98 to RR-101 (30 Sep 2026): commands recorded after the last migration, admitted as CURRENT records by the migration at _handoffs c3c0cbe. */
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-30_RR-98_REPAIR_THREE_REFERENCES_THEN_NEXT_ROW.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-30_RR-99_CONTINUE_FROM_30_90_AFTER_203.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-30_RR-100_REPAIR_F90_PREREQUISITE_THEN_CONTINUE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-30_RR-101_SAVE_AND_PAUSE.md", loader: "authority register (CURRENT record)" }),
  /* RR-102 §2 (30 Sep 2026): the owner's page-planning decision — direction only; no row, no board movement. */
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_DECISION_2026-09-30_RR-102_PAGE_PLANNING_THREE_NUMBERS.md", loader: "authority register (CURRENT record)" }),
  /* RR-102, F90 (30 Sep 2026): the command (a CURRENT record) and F90's acceptance, after the migration at _handoffs c3c0cbe. */
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-30_RR-102_FINISH_F90_PREREQUISITE_RECORD_PAGE_PLANNING.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F90_ACCEPTANCE_2026-09-30.md", loader: "F-board acceptance F90" }),
  /* RR-103, F75 (30 Sep 2026): the command (a CURRENT record) and F75's acceptance, after the migration at _handoffs 01275a9. */
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-30_RR-103_CLOSE_F90_ADD_PAGE_OPPORTUNITY_ROW_THEN_CONTINUE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F75_ACCEPTANCE_2026-09-30.md", loader: "F-board acceptance F75" }),
  /* RR-104 to RR-110 (30 Sep - 1 Oct 2026): seven commands admitted CURRENT by the migration at _handoffs d3c8e79 (RR-111). */
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-30_RR-104_IMPROVE_THE_COLLECTOR_PREPARE_ONE_BOUNDED_COLLECTION.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-30_RR-105_GREEN_RUN_THE_ONE_BOUNDED_COLLECTION.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-30_RR-106_RR-105_FAILURE_REPAIR_ONLY.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-10-01_RR-107_RUN_THE_ONE_BOUNDED_COLLECTION_UNDER_THE_FRESH_GREEN.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-10-01_RR-108_REPAIR_THE_PACER_CLASSIFY_THE_KEPT_EVIDENCE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-10-01_RR-109_213_MERGED_VERIFY_EVERY_GATE_BEFORE_ANY_NEW_COLLECTION.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-10-01_RR-110_PAUSE_THE_CRAWL_LOOP_CONTINUE_BUILDING.md", loader: "authority register (CURRENT record)" }),
  /* RR-111, F23 (1 Oct 2026): the command, the owner's every-limb refinement (both CURRENT records) and F23's acceptance, after the migration at _handoffs d3c8e79. */
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-10-01_RR-111_BUILD_F23_FROM_RECORDED_DATA.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-10-01_RR-111_EVERY_LIMB_RULE_REFINEMENT.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F23_ACCEPTANCE_2026-10-01.md", loader: "F-board acceptance F23" }),
  /* RR-111 §5 and §9, F27 (1 Oct 2026): F23's open owner decision (a CURRENT record), and F27's acceptance and its amendment, after the migration at _handoffs 93fa696. */
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OPEN_OWNER_DECISION_2026-10-01_RR-111_F23_EXCESSIVE_AND_WEAK_LINKS.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F27_ACCEPTANCE_2026-10-01.md", loader: "F-board acceptance F27" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F27_ACCEPTANCE_AMENDMENT_1_2026-10-01.md", loader: "F-board acceptance F27" }),
  /* RR-112 and RR-113 (1 Oct 2026): eight records admitted CURRENT by the migration at _handoffs 2048dd3 — the two commands, the F87 and F27 open decisions, the RR-112 decision list, F87's acceptance and amendment, and F91's acceptance. */
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-10-01_RR-112_RESOLVE_THE_F27_HEADER_CONTRADICTION.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-10-01_RR-113_CLOSE_RR-112_BUILD_THE_F91_PAGE_PLANNER.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OPEN_OWNER_DECISION_2026-10-01_RR-111_F27_HEADERS_AND_PUBLIC_EXPOSURE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OPEN_OWNER_DECISION_2026-10-01_RR-111_F87_SCOPE_OF_OPERATIONAL_MONITORING.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_RR-112_OUTSTANDING_OWNER_DECISIONS_2026-10-01.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F87_ACCEPTANCE_2026-10-01.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F87_ACCEPTANCE_AMENDMENT_1_2026-10-01.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F91_ACCEPTANCE_2026-10-01.md", loader: "F-board acceptance F91" }),
  /* RR-113 §9, F44 (1 Oct 2026): F44's acceptance, after the migration at _handoffs eecdfe4. */
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F44_ACCEPTANCE_2026-10-01.md", loader: "F-board acceptance F44" }),
  /* RR-114, F16 (1 Oct 2026): the command (a CURRENT record) and F16's acceptance, after the migration at _handoffs 29a7c2c. */
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-10-01_RR-114_BUILD_THE_PUBLIC_QUESTION_RESEARCH_INTAKE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F16_ACCEPTANCE_2026-10-01.md", loader: "F-board acceptance F16" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_CLARIFICATION_2026-09-28_RR-76_TEST_ONLY_PERMISSION_IS_GENERAL.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-28_RR-80_F07_A_LIMIT_IS_NOT_A_PERMISSION.md", loader: "authority register (CURRENT record)" }),
]);
