/**
 * 🔴 F07 §5.6 · THE MANDATORY-READING MANIFEST — DECLARED (23 September 2026).
 *
 * The files a builder or a command must read: every CURRENT authority record the F05 register resolves, every
 * acceptance source the F-board pins, and the configuration the board and the authority loaders read. Checked by
 * src/governance/mandatory-reading.mjs against the loaders in BOTH directions — a missing required source and a
 * sealed or protected entry each turn the check RED. Generated from the loaders at corpus governance commit
 * 1429928b4813 (now 2026-09-24); regenerate after every corpus migration — the
 * check fails loudly until you do, which is the point.
 *
 * Paths only. No content of any listed file is copied here.
 */
export const BOARD_AND_AUTHORITY_CONFIG = Object.freeze(["config/fboard/acceptances.mjs","config/fboard/capabilities.mjs","config/fboard/crosswalk.mjs","config/fboard/f-board.mjs","config/authority/corpus.mjs","config/authority/inclusion.mjs","config/evidence-roles.mjs"]);
export const MANDATORY_READING = Object.freeze([
  Object.freeze({ repo: "engine", path: "config/authority/corpus.mjs", loader: "F-board configuration" }),
  Object.freeze({ repo: "engine", path: "config/authority/inclusion.mjs", loader: "F-board configuration" }),
  Object.freeze({ repo: "engine", path: "config/evidence-roles.mjs", loader: "F-board configuration" }),
  Object.freeze({ repo: "engine", path: "config/fboard/acceptances.mjs", loader: "F-board configuration" }),
  Object.freeze({ repo: "engine", path: "config/fboard/capabilities.mjs", loader: "F-board configuration" }),
  Object.freeze({ repo: "engine", path: "config/fboard/crosswalk.mjs", loader: "F-board configuration" }),
  Object.freeze({ repo: "engine", path: "config/fboard/f-board.mjs", loader: "F-board configuration" }),
  Object.freeze({ repo: "engine", path: "PASS_BOUNDARIES_AMENDMENT_1.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "engine", path: "PASS_BOUNDARIES_AMENDMENT_2.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "engine", path: "PASS_BOUNDARIES_AMENDMENT_3.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "engine", path: "PASS_BOUNDARIES_AMENDMENT_4.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "engine", path: "PASS_BOUNDARIES_AMENDMENT_5.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "engine", path: "PASS_BOUNDARIES_AMENDMENT_6.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "engine", path: "PASS_BOUNDARIES_AMENDMENT_7.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "engine", path: "PASS_BOUNDARIES_SOURCE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_BETA_G_RULING_9_AMBIGUOUS_2026-09-13_NIGHT.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-19_ERROR_REGISTER_AND_PERSISTENCE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-19_ROW17_CLOSE_OR_HALT.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-19_ROW9_CLOSE_OR_HALT.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-19_SELECT_AND_CLOSE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-20_ROW6_CLOSE_OR_HALT.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-20_ROW6_OWNER_INPUT_AND_CLOSE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-21_AMEND_ROW61_AND_RESUME_ROW6.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-21_ROW25_COMPLETE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-21_ROW4_COMPLETE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-21_ROW50_COMPLETE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-21_ROW50_OWNER_REOPEN_APPLIED.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-21_ROW6_DEMAND_RESEARCH_AND_CLOSE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-22_F05_CHAIN_PART3_REMEDIATION.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-22_F05_CHAIN_PART4_OWNER_ANSWERS.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-22_F05_CURRENT_AUTHORITY_REGISTER_CHAIN.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-22_F08_CONTRADICTORY_EVIDENCE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-22_ROW5_COMPLETE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-23_F07_COMPLETE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-23_F07_SINK_REPAIR.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-23_F08_COMPLETE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-24_BRANCH_DISPOSITION.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-24_AUDIT_STORE_PRIMITIVES.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-24_F01_COMPLETE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-24_F02_POST_MERGE_PREREQUISITES.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-24_F02_TENANT_ISOLATION.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-24_F06_COMPLETE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-24_F06_CORRECTION.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-24_PRIMITIVES_AND_SESSION_SAVE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-25_F02_DISPOSITION.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-25_F03_SUBJECT_ROOT_AND_CONNECTOR_REGISTRY.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-25_F03_CLOSE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-25_F04_ROLES_PERMISSIONS_APPROVALS.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-25_F04_POST_MERGE_CLOSE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-25_F09_CROSS_CLIENT_PORTABILITY.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-25_F09_OPTION_A_EXTERNAL_SUBJECT.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-25_F09_CLOSE_OUT.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-25_F10_COMPLETE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-25_F10_DEPENDENCY_PREPARATION.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-25_F10_PREP_ROUND2.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-25_F10_PREP_ROUND3.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-25_F07_NARROW_AMENDMENT_REISSUE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-26_F07_AMENDMENT_1_POST_MERGE_CLOSE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-26_SHEET_SAFE_LABELS.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-26_F10_OWNER_SHEET.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-26_RA4_SAFE_LABELS_RULING.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-26_F10_OWNER_INPUT_HOLD.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-26_F10_OWNER_DECISION_GATE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-26_F10_RESOLVE_GATE_AND_ADVANCE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-26_F10_OWNER_DIRECTION_OF1_OF4.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-26_F10_FREEZE_BUILD_SELECT.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-26_F07_AMENDMENT_2_MARKING_KEY_EVALUATOR.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F10_OWNER_DECISION_GATE_2026-09-26.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F10_OWNER_DECISIONS_STATUS_2026-09-26.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-26_RA4_SAFE_DISPLAY_LABELS.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-26_F10_RESUME_EXTERNAL_SEALED_KEY.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-26_F10_STORAGE_S.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-26_F10_SCORER_ROUTE_AND_MISSING_OUTPUT.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-26_F10_ALLOCATION_ADOPTED.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-26_F10_OF4_AMENDMENT_1_DECIDED.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-26_F10_PR165_CLOSE_AND_C7_AMENDMENT.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-26_F10_C7_SCOPE_DECISION.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-26_F10_C7_BAR_APPROVAL_FREEZE_AND_IMPLEMENT.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-26_F10_C7_COMPLETION_PATH.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-26_REPAIR_D_RECORDER_1_THEN_RESUME.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-26_168_MERGED_CONTINUE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-27_CONTINUE_F10_AFTER_169.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-27_POST_MERGE_170_STORAGE_S_BOUNDARY_THEN_SELECTION.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-27_WITHDRAW_CI_SCOPE_PROCEED_UNDER_STORAGE_S.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-27_REPAIR_171_BEFORE_MERGE_PRESERVE_SEAL.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F01_FROZEN_ACCEPTANCE_2026-09-24.md", loader: "F-board acceptance F01" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F02_ACCEPTANCE_2026-09-24.md", loader: "authority register (CURRENT record) — the original F02 acceptance, amended by Amendment 1" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F02_ACCEPTANCE_AMENDMENT_1_2026-09-25.md", loader: "F-board acceptance F02" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F03_FROZEN_ACCEPTANCE_2026-09-25.md", loader: "F-board acceptance F03" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F04_ACCEPTANCE_2026-09-25.md", loader: "authority register (CURRENT record) — the original F04 acceptance, amended by Amendment 1" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F04_ACCEPTANCE_AMENDMENT_1_2026-09-25.md", loader: "F-board acceptance F04" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F09_ACCEPTANCE_2026-09-25.md", loader: "F-board acceptance F09" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F10_ACCEPTANCE_2026-09-26.md", loader: "authority register (CURRENT record) — the original F10 acceptance, amended by Amendment 1" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F10_ACCEPTANCE_AMENDMENT_1_2026-09-26.md", loader: "authority register (CURRENT record) — Amendment 1, amended by Amendment 2" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F10_ACCEPTANCE_AMENDMENT_2_2026-09-27.md", loader: "authority register (CURRENT record) — Amendment 2, amended by Amendment 3" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F10_ACCEPTANCE_AMENDMENT_3_2026-09-28.md", loader: "F-board acceptance F10" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-27_PR171_AUDIT_INCIDENT_RECONCILE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-27_FINISH_F10_ON_FROZEN_CONTRACT.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-27_FINISH_F10_CONTINUE_AFTER_171_MERGE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-27_F10_REAL_HELDOUT_EVALUATION.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-28_PRODUCT_DIRECTION_AND_REUSE_MEASUREMENT.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-28_APPLY_BEST_PAGE_RECIPE_V3_TO_REUSE_CENSUS.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_CC_COMMAND_2026-09-27_CORRECT_V3_ADOPTION_AND_RECOVER_F10.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-28_V3_ADOPTION.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F06_FROZEN_ACCEPTANCE_2026-09-24.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F07_FROZEN_ACCEPTANCE_2026-09-23.md", loader: "F-board acceptance F07" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F07_ACCEPTANCE_AMENDMENT_1_2026-09-25.md", loader: "authority register (CURRENT record) — Amendment 1, amended by Amendment 2" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F07_ACCEPTANCE_AMENDMENT_2_2026-09-26.md", loader: "authority register (CURRENT record) — Amendment 2, amended by Amendment 3" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_F07_ACCEPTANCE_AMENDMENT_3_2026-09-26.md", loader: "F-board acceptance F07" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_FEATURE_MASTER_COMMAND_ROW1_2026-09-18.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_FEATURE_MASTER_COMMAND_ROW5_2026-09-18.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_FEATURE_MASTER_COMMAND_ROW9_2026-09-18.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_CLARIFICATION_2026-09-19_PRODUCT_PRIORITY_AND_ISOLATION_BOUNDARY.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_DECISION_2026-09-19_ROW1_CLOSED_BLOCKED_PROVED.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_DECISION_2026-09-22_ROW50_PRODUCT_BOUNDARY.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_DECISION_2026-09-24_F02_RELOCATE_SINGLE_CLIENT_TOOLS.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-13_AMENDMENT_4_SCOPE_OPENS.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-13_AMENDMENT_5_PORTABLE_PAGE_CONSTRUCTION.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-19_ARTEFACT_PERSISTENCE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-19_COMMIT_MECHANISM_SCOPE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-19_D2_MIXED_LIMB_SPLIT.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-19_U1_ROW1_COST_ISOLATION_SEMANTICS.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-21_ROW4_CONJUNCTION_AND_REASONING.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-21_ROW50_LABEL_ON_FACE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-21_TENANT_RESOURCE_ATTACHMENTS.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-22_BOARD_AUTHORITY.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-22_F05_ACCEPTANCE.md", loader: "F-board acceptance F05" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-22_F08_ACCEPTANCE.md", loader: "F-board acceptance F08" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-22_F08_GOVERNED_WRITE_BOUNDARY.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-22_HELDOUT_ROLE_SCOPE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-22_RETIRED_CONTAMINATED_HELDOUT.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-23_F08_TARGET_AWARE_DURABILITY.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-24_AUDIT_STORE_ONLY_PRIMITIVES.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-24_F02_RESOURCE_ATTACHMENTS.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_A_2026-09-15_READ_ONLY_DEPLOY_KEY.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULINGS_2026-09-14_ROWS_5_6_STATES.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-25_F04_ZERO_APPROVED_ACTION_POPULATION.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_RULING_2026-09-25_F02_DISPOSITION.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_OWNER_STATUS_SEMANTICS_RULING_RECORD_2026-09-18.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "AlmiVisibility_ROW61_OWNER_DECISION_2026-09-15.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "CC_COMMAND_2026-09-13_SESSION_SAVE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "CC_COMMAND_2026-09-14_OPTION_A_SUBJECT_REGISTRY_LEAVES_THE_REPO.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "CC_COMMAND_2026-09-14_ROWS_5_6_INTENT_CLUSTERING_AXIS_DISCOVERY.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "CC_COMMAND_2026-09-15_GAP1_UNGATED_WRITERS.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "CC_COMMAND_2026-09-15_GAP3_ARCHIVE_CORPUS_OUT_ROW36.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "CC_COMMAND_2026-09-15_RENDERER_LIVE_ONCE_ON_MAIN.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "CC_COMMAND_2026-09-15_ROW25_PAGE_QUALITY_GATE.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "CC_COMMAND_2026-09-15_ROW3_SEARCH_LANGUAGE_OWNED_HALF.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "CC_COMMAND_2026-09-15_ROW36_DCRW4_GUARD.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "CC_COMMAND_2026-09-15_ROW36_DESTRUCTIVE_GUARDS.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "CC_COMMAND_2026-09-15_ROW4_LOCALIZED_THINKING.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "CC_COMMAND_2026-09-15_ROW7_MARKET_MEASUREMENT_OWNED_HALF.md", loader: "authority register (CURRENT record)" }),
  Object.freeze({ repo: "governance", path: "CC_COMMAND_AMENDMENT_3_ROWS_59_60.md", loader: "authority register (CURRENT record)" }),
]);
